# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];
  boot = {
    initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
    kernelPackages = pkgs.linuxPackages_6_6;
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [
      pkgs.linuxKernel.packages.linux_6_6.system76-power
      pkgs.linuxKernel.packages.linux_6_6.system76-scheduler
    ];
    extraModprobeConfig = "options bluetooth disable_ertm=1 ";
  }; # This is to allow Xbox controller to work
  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXROOT";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/NIXBOOT";
    fsType = "vfat";
  };

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  powerManagement = {
    enable = true;
    powertop.enable = true;
    cpuFreqGovernor = "ondemand";
  };
  nix.settings.max-jobs = lib.mkDefault 8;
}
