name: Cachix
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Clone repo
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Install nix
      - uses: cachix/install-nix-action@v18
      - name: Cachix setup
        uses: cachix/cachix-action@v12
        with:
          name: YOURNAME
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Build private-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/private-laptop/configuration.nix -I nixpkgs=./nix/nixos-unstable -A system
      - name: Cache private-laptop system derivation
        run: realpath result | cachix push YOURNAME
